# Generated by Django 4.0.5 on 2022-06-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='edad',
            new_name='annonacimiento',
        ),
    ]
