# Generated by Django 4.0.5 on 2022-06-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0002_rename_edad_familia_annonacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='annonacimiento',
            field=models.DateField(),
        ),
    ]
